kwt=0.5#light atenuation coefficient (water clarity)
d=4# depth (length of the rope we have for measuring irradiance)
mew0 = 0.1
ps=50 #density
km= 0.006 #specific light attenuation coefficient for foil
k1=90 #half saturation constant
thetag=1.06#Arrhenius constant for growth
delta=0 #loss rate
tb = 10 #base temperature
mew1 = 0.4# carb use rate
mew1 = 0.4# density required to use carbohydrates at 50% capacity
chm = 50 #likely bad estimate
days = 100 # likely bad estimate
lambda0= 0.01
thetar = 1.072
tempAmp = 25
tempPhase = 80
iradianceAmp = 50
iradiancePhase = 115
